image: archlinux

packages:
  - tree-sitter-cli

sources:
  - https://git.sr.ht/~klahr/quadrate.nvim

tasks:
  - test_grammar: |
      cd quadrate.nvim/tree-sitter-quadrate
      tree-sitter generate
      tree-sitter test

triggers:
  - action: email
    condition: failure
    to: klahr@r8.rs
