image: debian/testing

secrets:
  - 380b3418-72be-46d4-bc76-c0178407accc

packages:
  - nodejs
  - npm

sources:
  - git+ssh://git@git.sr.ht/~klahr/quadrate.nvim

environment:
  GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"

tasks:
  - install_tree_sitter: |
      sudo npm install -g tree-sitter-cli
  - test_grammar: |
      cd quadrate.nvim/tree-sitter-quadrate
      tree-sitter generate
      tree-sitter test

triggers:
  - action: email
    condition: failure
    to: klahr@r8.rs
