image: debian/testing

packages:
  - nodejs
  - npm

sources:
  - https://git.sr.ht/~klahr/quadrate.nvim

tasks:
  - install_tree_sitter: |
      sudo npm install -g tree-sitter-cli
  - test_grammar: |
      cd quadrate.nvim/tree-sitter-quadrate
      tree-sitter generate
      tree-sitter test

triggers:
  - action: email
    condition: failure
    to: klahr@r8.rs
