image: debian/testing

secrets:
  - 380b3418-72be-46d4-bc76-c0178407accc

packages:
  - nodejs
  - npm

sources:
  - git+ssh://git@git.sr.ht/~klahr/quadrate.nvim

environment:
  GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"

tasks:
  - install_tree_sitter: |
      sudo npm install -g tree-sitter-cli
  - test_grammar: |
      cd quadrate.nvim/tree-sitter-quadrate
      tree-sitter generate
      tree-sitter test
  - mirror-to-github: |
      cd ~/quadrate.nvim
      ssh-keyscan github.com >> ~/.ssh/known_hosts
      git remote add github git@github.com:quadrate-language/quadrate.nvim.git || \
        git remote set-url github git@github.com:quadrate-language/quadrate.nvim.git
      git push --mirror github

triggers:
  - action: email
    condition: failure
    to: klahr@r8.rs
